#!/usr/bin/env bash

CURRENT=`pwd`

python "$CURRENT/blog.py"

cd /tmp
mkdir blogwork
cd blogwork

git clone git@github.com:ericflo/ericflo.github.com.git
cd ericflo.github.com

git checkout --orphan master
git rm -rf .

cp -R $CURRENT/output/* .
touch .nojekyll
echo "eflorenzano.com" > CNAME

git add .
git commit -a -m "Generate blog site"
git push origin master --force

cd /tmp
rm -Rf /tmp/blogwork